name: Linkspector

on:
  pull_request:
  push:
    branches:
      - unstable

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-links:
    name: runner / linkspector
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1.1.3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          config_file: .github/.linkspector.yml
          fail_on_error: true
          filter_mode: nofilter
